env: "dev"
http_server:
  http_address: "0.0.0.0:8080" # set port while docker run
  timeout: 4s
  idle_timeout: 60s
db_server:
  db_address: "postgres"
  port: 5432
  user: "myuser"
  password: "mypassword"
  dbname: "mydatabase"
