env: "dev"
http_server:
  http_address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
db_server:
  db_address: "localhost"
  port: 5432
  user: "myuser"
  password: "mypassword"
  dbname: "mydatabase"
